// ============================================================
// supabase/functions/_shared/types.ts
// Central type definitions shared across all edge functions
// ============================================================

// ── Agent Config ─────────────────────────────────────────────
// The central data structure. Everything the agent needs to run.
// Generated by EF2, interpreted by EF3. No code — only JSON.

export type IntentCategory =
  | 'sales'
  | 'support'
  | 'research'
  | 'data'
  | 'creative'
  | 'utility'

export type ToolName =
  | 'web_search'
  | 'scrape_url'
  | 'summarize'
  | 'extract_data'
  | 'send_email'

export type LLMProvider = 'openai' | 'anthropic'

export interface SchemaField {
  type: 'string' | 'number' | 'boolean' | 'object' | 'array'
  description?: string
  required?: boolean
}

export interface AgentConfig {
  agent_id:      string
  version:       number
  name:          string
  description:   string
  intent:        IntentCategory
  provider:      LLMProvider          // which LLM to use — openai | anthropic
  system_prompt: string
  tools:         ToolName[]
  input_schema:  Record<string, SchemaField>
  output_schema: Record<string, SchemaField>
  constraints:   string[]
  max_steps:     number               // default 5, max 10
  test_cases:    TestCase[]
}

export interface TestCase {
  input:             Record<string, unknown>
  expected_contains: string[]         // keys that must exist in output
}

// ── Agent Spec ───────────────────────────────────────────────
// Intermediate representation from EF1 before EF2 produces final config

export interface AgentSpec {
  intent:             IntentCategory
  name:               string
  description:        string
  recommended_tools:  ToolName[]
  system_prompt:      string
  constraints:        string[]
  input_schema:       Record<string, SchemaField>
  output_schema:      Record<string, SchemaField>
  test_cases:         TestCase[]
}

// ── Tool Calling ─────────────────────────────────────────────
// Normalized internal representation — adapters convert
// OpenAI tool_calls[] and Anthropic tool_use blocks to this

export interface ToolCall {
  id:        string
  tool_name: ToolName
  arguments: Record<string, unknown>
}

export interface ToolResult {
  tool_call_id: string
  tool_name:    ToolName
  output:       string              // always stringified for LLM context
  error?:       string
}

// ── LLM Messages ─────────────────────────────────────────────
// Normalized message format for conversation history

export type MessageRole = 'system' | 'user' | 'assistant' | 'tool'

export interface Message {
  role:          MessageRole
  content:       string
  tool_calls?:   ToolCall[]         // present when role = assistant + LLM requested tools
  tool_call_id?: string             // present when role = tool
  tool_name?:    string             // present when role = tool
}

// ── LLM Response ─────────────────────────────────────────────
// Normalized response from llm_client.ts — hides provider differences

export type LLMResponseType = 'final_answer' | 'tool_calls' | 'error'

export interface LLMResponse {
  type:        LLMResponseType
  content?:    string               // present when type = final_answer
  tool_calls?: ToolCall[]           // present when type = tool_calls
  error?:      string               // present when type = error
  usage?: {
    prompt_tokens:     number
    completion_tokens: number
    total_tokens:      number
  }
}

// ── Runner Result ─────────────────────────────────────────────
// Return value of EF3 (agent-runner)

export interface RunResult {
  output:       Record<string, unknown>   // final structured output
  steps_taken:  number
  latency_ms:   number
  tokens_used:  number
  messages:     Message[]                 // full trace for playground
  errors:       string[]
}

// ── Review Result ─────────────────────────────────────────────
// Return value of EF4 (agent-reviewer)

export interface ReviewMetrics {
  accuracy:             number    // 0-100
  latency:              number    // 0-100
  format:               number    // 0-100
  constraint_adherence: number    // 0-100
}

export interface ReviewResult {
  pass:          boolean
  score:         number           // weighted average 0-100
  metrics:       ReviewMetrics
  issues:        string[]
  suggested_fix: string | null    // injected into EF2 on retry, null if passing
}

// ── Job Status ───────────────────────────────────────────────
// All valid values for agent_jobs.status

export type JobStatus =
  | 'queued'
  | 'generating_spec'
  | 'generating_config'
  | 'running_sandbox'
  | 'reviewing'
  | 'live'
  | 'needs_review'
  | 'failed'

// ── Edge Function Payloads ───────────────────────────────────
// Request/response shapes for each edge function

export interface EF1Payload {
  job_id:     string
  user_id:    string
  raw_prompt: string
  provider?:  LLMProvider
}

export interface EF1Response {
  spec: AgentSpec
}

export interface EF2Payload {
  job_id:       string
  user_id:      string
  agent_id:     string
  spec:         AgentSpec
  fix_context?: string          // injected on retry with reviewer's suggested_fix
  provider?:    LLMProvider
}

export interface EF2Response {
  config_path: string
  config:      AgentConfig
}

export interface EF3Payload {
  job_id:   string
  user_id:  string
  config:   AgentConfig
  input:    Record<string, unknown>
}

export interface EF3Response extends RunResult {}

export interface EF4Payload {
  job_id:      string
  config:      AgentConfig
  test_case:   TestCase
  output:      Record<string, unknown>
  latency_ms:  number
  errors:      string[]
}

export interface EF4Response extends ReviewResult {}

export interface EF5Payload {
  agent_id: string
  user_id:  string
  input:    Record<string, unknown>
  source:   'playground' | 'embed' | 'api'
}

export interface EF5Response extends RunResult {}